export const APOLLO_CLIENT_CONTEXT = 'APOLLO_CLIENT_CONTEXT';
export const APOLLO_CONTEXT = 'APOLLO_CONTEXT';
export const FETCH_POLICY = {
  NETWORK_ONLY: 'network-only',
  NOCACHE: 'no-cache',
};
export const WAIT_RESPONSE_TIMEOUT = 100;
export const DEFAULT_ERROR_POLICY = 'all';

export const GET_QUERY = 'GQL.GET_QUERY';
export const GET_QUERY_SUCCESS = 'GQL.GET_QUERY_SUCCESS';
export const GET_QUERY_ERROR = 'GQL.GET_QUERY_ERROR';
export const GET_QUERY_LOADING = 'GQL.GET_QUERY_LOADING';
export const MUTATE_QUERY = 'GQL.MUTATE_QUERY';
export const MUTATE_QUERY_SUCCESS = 'GQL.MUTATE_QUERY_SUCCESS';
export const MUTATE_QUERY_ERROR = 'GQL.MUTATE_QUERY_ERROR';
export const MUTATE_QUERY_LOADING = 'GQL.MUTATE_QUERY_LOADING';
export const SUBSCRIPTION_QUERY = 'GQL.SUBSCRIPTION_QUERY';
export const SUBSCRIPTION_QUERY_SUCCESS = 'GQL.SUBSCRIPTION_QUERY_SUCCESS';
export const SUBSCRIPTION_QUERY_ERROR = 'GQL.SUBSCRIPTION_QUERY_ERROR';
export const RESET_CACHE = 'GQL.RESET_CACHE';
export const RESET_CACHE_SUCCESS = 'GQL.RESET_CACHE_SUCCESS';
export const DELAY_ACTION = 'GQL.DELAY_ACTION';
